name: A
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      flag:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  echo-flag-eq-false:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag == false && 'false' || 'true' }}"
