name: A
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      flag:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  echo-flag-eq-true:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag == true && 'true' || 'false' }}"

  echo-flag-eq-false:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag == false && 'true' || 'false' }}"

  echo-flag-eq-null:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag == null && 'true' || 'false' }}"

  echo-to-json-flag-eq-string-true:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) == 'true' && 'true' || 'false' }}"

  echo-to-json-flag-eq-string-false:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) == 'false' && 'true' || 'false' }}"

  echo-to-json-flag-eq-string-null:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) == 'null' && 'true' || 'false' }}"
