name: A
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      flag:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  echo-flag-eq-true:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag == true && 'true' || 'false' }}"

  echo-flag-eq-false:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag == false && 'true' || 'false' }}"

  echo-flag-eq-null:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag == null && 'true' || 'false' }}"

  echo-flag-neq-true:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag != true && 'true' || 'false' }}"

  echo-flag-neq-false:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag != false && 'true' || 'false' }}"

  echo-flag-neq-null:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ inputs.flag != null && 'true' || 'false' }}"
