name: A
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      flag:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  echo-flag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) }}"

  check-and-echo-flag:
    if: inputs.flag
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) }}"

  check-and-echo-flag-eq-true:
    if: inputs.flag == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) }}"

  echo-github-event-flag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(github.event.inputs.flag) }}"

  check-and-echo-github-event-flag:
    runs-on: ubuntu-latest
    if: github.event.inputs.flag
    steps:
      - run: echo "flag=${{ toJSON(github.event.inputs.flag) }}"

  check-and-echo-github-event-flag-eq-string-true:
    runs-on: ubuntu-latest
    if: github.event.inputs.flag == 'true'
    steps:
      - run: echo "flag=${{ toJSON(github.event.inputs.flag) }}"

  check-and-echo-from-json-github-event-flag:
    runs-on: ubuntu-latest
    if: fromJSON(github.event.inputs.flag)
    steps:
      - run: echo "flag=${{ toJSON(github.event.inputs.flag) }}"

  check-and-echo-from-json-github-event-flag-eq-string-true:
    runs-on: ubuntu-latest
    if: fromJSON(github.event.inputs.flag == 'true')
    steps:
      - run: echo "flag=${{ toJSON(github.event.inputs.flag) }}"
