name: A
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      flag:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  echo-flag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) }}"

  check-and-echo-flag:
    if: inputs.flag
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) }}"

  check-and-echo-flag-eq-true:
    if: inputs.flag == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(inputs.flag) }}"

  echo-github-event-flag:
    runs-on: ubuntu-latest
    steps:
      - run: echo "flag=${{ toJSON(github.event.inputs.flag) }}"

  check-and-echo-github-event-flag:
    runs-on: ubuntu-latest
    if: github.event.inputs.flag
    steps:
      - run: echo "flag=${{ toJSON(github.event.inputs.flag) }}"

  check-and-echo-github-event-flag-eq-string-true:
    runs-on: ubuntu-latest
    if: github.event.inputs.flag == 'true'
    steps:
      - run: echo "flag=${{ toJSON(github.event.inputs.flag) }}"

  call-b-workflow-flag:
    uses: ./.github/workflows/b.yml
    with:
      flag: ${{ inputs.flag }}

  call-b-workflow-flag-eq-true:
    uses: ./.github/workflows/b.yml
    with:
      flag: ${{ inputs.flag == true }}

  call-b-workflow-github-event-flag:
    uses: ./.github/workflows/b.yml
    with:
      flag: ${{ github.event.inputs.flag }}

  call-b-workflow-github-event-eq-string-flag:
    uses: ./.github/workflows/b.yml
    with:
      flag: ${{ github.event.inputs.flag == 'true' }}

  call-b-workflow-from-json-github-event-flag:
    uses: ./.github/workflows/b.yml
    with:
      flag: ${{ fromJSON(github.event.inputs.flag) }}

  call-b-workflow-from-json-github-event-eq-string-flag:
    uses: ./.github/workflows/b.yml
    with:
      flag: ${{ fromJSON(github.event.inputs.flag == 'true') }}
