name: B
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      flag:
        type: boolean
        default: false

defaults:
  run:
    shell: bash

jobs:
  call-c-workflow-flag:
    uses: ./.github/workflows/c.yml
    with:
      flag: ${{ inputs.flag }}

  call-c-workflow-github-event-flag-string:
    uses: ./.github/workflows/c.yml
    with:
      flag: ${{ github.event.inputs.flag }}

  call-c-workflow-from-json-github-event-flag-string:
    uses: ./.github/workflows/c.yml
    with:
      flag: ${{ fromJSON(github.event.inputs.flag) }}
